### ISSUE TITLE
node imagemin

### ISSUE THREAD

**Issue by felipeschmitz** [codecasts/ambientum#101]
ola, estou tendo problemas ao executar o comando "n npm run dev", ao que tudo indica pelo erro é que não está compactando as imagens pelo "imagemin".

Alguém tem uma solução para isso?

**Comment by hernandev** [comment]
@felipeschmitz fechando a issue por falta de mais detalhes, logs, mensagens de erro, caso ainda tenha problemas, favor reabrir. Obrigado
