### ISSUE TITLE
xDebug does not work

### ISSUE THREAD

**Issue by cichondev** [codecasts/ambientum#104]
Hello guys,

I'm trying to set up xDebug in a project but it does not work!
I set the variable "XDEBUG_ENABLED = true" in the docker-compose service, as print below:
![docker-compose-2](https://user-images.githubusercontent.com/9503433/42776366-21ec6c1e-890d-11e8-8f47-630b0d7b0fff.png)

In PhpStorm, I configured a server, and the debug settings, as follows in the print.
![phpstorm_configs](https://user-images.githubusercontent.com/9503433/42776008-3bd96696-890c-11e8-9334-f5f874aeb882.png)

In PhpStorm I select the breakpoints, start the debug, and update the application, but the request is processed normally, ignoring the breakpoints.
The impression I have is that the xDebug container is not able to send the debug information to my machine, but I have no idea how to resolve this.

OS: Ubuntu 18.04
Would you have any suggestions? Thank you!

**Comment by jansenfelipe** [comment]
Hi @cichondev !

Run `docker-compose run webservice php --info | grep xdebug` and paste result here.

We have to check exactly how the xdebug extension configuration. The problem may be in many places.. 😕

**Comment by hernandev** [comment]
Thanks for helping out while I was out @jansenfelipe ! you guys are awesome.

xDebug on Docker uses the reverse connection method.

It means you must use the IDE to start listening for the connection the container will be doing on the host.

By default, the xDebug connect port is 9000. The IDE listen on 9000 while the container connects to the host using that port.

It means on the IDE, it should be 9000 where you put 8080.

The container will automatically detect the IP address of the host (docker network) based on the internet gateway strategy.

It also means custom networking will probably not work.

I'll work as soon as possible on a reverse strategy.

Thank you all, closing for now, if the problem persists and still relevant to you, please reopen or start a new thread 

Thank you!

**Comment by hernandev** [comment]
Also, please see #103 for a more in-depth reference and updates on the issue
