### ISSUE TITLE
example project with laravel and vue?

### ISSUE THREAD

**Issue by g0ld3lux** [codecasts/ambientum#11]
Laravel project with a Docker-compose file is pretty straight forward...
just create a docker-compose.yml
and do docker-compose up

I wanna know how you develop laravel and vue hand in hand with vue-cli....
ive seen that your example is vueJs only...
where your vuejs app is the current directory
and the dist is for the production...

so if you where to have laravel and vuejs developing at the same time...
how would the workflow be?

can you share some info , tips, insights 

THanks

**Comment by wilcorrea** [comment]
I dont know you already saw, but here go https://github.com/codecasts/spa-starter-kit ; )
