### ISSUE TITLE
Access the redis container

### ISSUE THREAD

**Issue by jffsx** [codecasts/ambientum#111]
What is the command to access the redis container?

**Comment by pedrommone** [comment]
Hello @jffsx 

You can use `docker exec -it container_hash redis-cli`. The `container hash` you can get using `docker ps`.

**Comment by hernandev** [comment]
docker-compose run [service-name] [command]

if you named your service for redis as the example files on this repo, and that name is `cache`

you can do:

`docker-compose run cache sh`

Notice sh is the shell for the container, since most minimal images don't come with bash installed.

**Comment by jffsx** [comment]
Hi guys

Sorry for the delay in answering. Many thanks @pedrommone 

I accessed it this way, what I found odd is that the keys were not being created `keys *`, however, the application was 'cached'.

Thank's guys
