### ISSUE TITLE
Fix for 'PDOException with message 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known'

### ISSUE THREAD

**Issue by g0ld3lux** [codecasts/ambientum#14]
Our Command Bash is limited to default network...
By Default you are not using the default network...
since it will create a new name of network based on your app Name
using php command will always yield an error 
```
PDOException with message 'SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known'
```
So I made a new Command called artisan
```
function artisan() {
	docker run -it --rm -v $(pwd):/var/www/app -v $A_COMPOSER_MOUNT -v $A_SSH_PHP_MOUNT --network=$1 --link $2:mysql ambientum/php:7.0 php artisan "$3"
}
alias artisan=artisan
```

we can use it as follows
```
artisan network_name container_id_or_name artisan_commands
```

so for example
artisan docker53_default docker53_mysql migrate

**Comment by hernandev** [comment]
For running commands on a compose defined network, its probably a better ideia to run it against a container that is compose defined.

That's how you can do it:

```
docker-compose run [service-name] [command]
```

so for example if you want to migrate

```
docker-compose run app php artisan migrate
```

on this case, i'm considering the web service name is `app`, name it as you named the service inside docker-compose container


you can alias artisan in a better way

```
alias artisan='docker-compose run app php artisan'
```

and them just use

```
artisan migrate
```

This way, the container will have connection to all the links defined inside docker-compose.yml, and the .env file will be valid against both
