### ISSUE TITLE
Error ao rodar "p composer install"

### ISSUE THREAD

**Issue by raisiqueira** [codecasts/ambientum#18]
![captura de tela de 2016-12-27 16-18-47](https://cloud.githubusercontent.com/assets/2914170/21506611/2e21651e-cc50-11e6-9897-78c38aca3710.png)

When running the command `p composer install` the error on the image is returned, even if for the first time running `p composer update`.

**Comment by hernandev** [comment]
Opa, @raisiqueira atualize o arquivo `~/.ambientum_rc`, fiz alterações a poucas horas que devem resolver esse problema.

Caso precise resolver manualmente.

rode os comandos

`chown -R $(whoami):$(whoami) ~/.cache/ambientum`
