### ISSUE TITLE
How to install PHP extensions?

### ISSUE THREAD

**Issue by julihermes** [codecasts/ambientum#21]
I need to install the extensions bcmath, for a project in my job.

**Comment by hernandev** [comment]
most extensions are already enabled by default, you you need one that is not default supported, you can submit a pull request if it is of general interest.

otherwise, fork the project and adjust the corresponding Dockerfile with the extensions you need.

**Comment by hernandev** [comment]
@julihermes I'm including bcmath on the original image as now, the images with that extension bundled by default should be available in a few hours.

**Comment by julihermes** [comment]
wow, thanks a lot!! :)

**Comment by hernandev** [comment]
just pull the new images, they are already available

**Comment by deyvisonrocha** [comment]
commit reference 
https://github.com/codecasts/ambientum/commit/1ee7313778e322ccef32b470d0923eed86aeda07
