### ISSUE TITLE
MongoDB Image

### ISSUE THREAD

**Issue by ptitkiller** [codecasts/ambientum#24]
Thank you very much for this package. I'm using spa-starter-kit and I find it also very excellent. I have worked with mongodb to save log, and now php work with mongodb is also very easy. I hope you can create more a image mongodb.
Again thank you very much.

**Comment by hernandev** [comment]
Ki @ptitkiller PHP images of Ambientum already have support on the mongdb extesion, you can safely use the official docker image with ambientum. just include them in your `docker-compose.yml` file

**Comment by hernandev** [comment]
@ptitkiller closed this by inactivity, let me know if you need any further help getting MongoDB to work along with the other Ambientum images
