### ISSUE TITLE
Update PHP 7.1 to 7.1.2

### ISSUE THREAD

**Issue by pedrommone** [codecasts/ambientum#25]
Heres the changelog: http://php.net/ChangeLog-7.php#7.1.2

Since the container download the last php version itself, we need just run the build again.

**Comment by hernandev** [comment]
The last build was a few days ago, current version os 7.1.1.

Running the new build to make 7.1.2 available

**Comment by pedrommone** [comment]
Awesome!

**Comment by hernandev** [comment]
@pedrommone 7.1 is provided by https://deb.sury.org/ packaging, not compiled from source, I'm checking out if 7.1.2 is already available but looks like not yet. usually it only takes a couple of days until released on the repo

**Comment by hernandev** [comment]
One idea is to migrate the images to a from-source compiled version, to keep track of old versions building as well, unfortunately, it will have to wait at least a few weeks for this change to take place, for now let's just wait a little bit

**Comment by hernandev** [comment]
To keep progress on Build from source on Alpine:

https://github.com/codecasts/ambientum/blob/php-alpine/php-alpine/7.1/Dockerfile
