### ISSUE TITLE
sed command removing listen.group fpm config on pool.d/www.conf

### ISSUE THREAD

**Issue by caiquecastro** [codecasts/ambientum#27]
The command `sed -i "/group = .*/c\group = php-user" /etc/php/7.1/fpm/pool.d/www.conf` is adjusting the group config but it's replacing the listen.group config by a duplicated group entry.

For example, if the initial config looks like:

```
user = www-data
group = www-data

listen.owner = www-data
listen.group = www-data
```

after this command, it will look like:

```
user = www-data
group = php-user

listen.owner = www-data
group = php-user
```

https://github.com/codecasts/ambientum/blob/master/php/7.1/Dockerfile#L76

https://github.com/codecasts/ambientum/blob/master/php/7.0/Dockerfile#L75

**Comment by hernandev** [comment]
@caiquecastro indeed I've noticed this problem, I'll take a look in how to fix it

**Comment by hernandev** [comment]
@caiquecastro please add a second fix there, listen.owner is set on the Dockerfile as being listen.user, that also needs to be fixed

**Comment by hernandev** [comment]
it does not has any side effects as it is right now because php is listening with TCP on port 9000. not on file, but since that can be changed, it needs to be correctly set
