### ISSUE TITLE
Shell auto install

### ISSUE THREAD

**Issue by hernandev** [codecasts/ambientum#31]
@julihermes I've built a command line installed so people can easily setup Ambientum on their machines:

```
curl -sSL https://goo.gl/KhJecM | bash
```
The above command will automatically fetch the installer.sh script, detect the user terminal, download the corresponding alias file and make sure it is auto started on terminal launches.

Can you test the windows version and provide the adjusts for proper initialization on windows? I don't have a windows machine to test right now

**Comment by julihermes** [comment]
Yes, tomorrow maybe I have a free time or in carnaval, but soon I will test!!!

**Comment by hernandev** [comment]
Thanks man, take your time is not urgent

On Feb 22, 2017 8:01 PM, "Julihermes Melo" <notifications@github.com> wrote:

Yes, tomorrow maybe I have a free time or in carnaval, but soon I will
test!!!

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/codecasts/ambientum/issues/31#issuecomment-281833778>,
or mute the thread

**Comment by hernandev** [comment]
This issue is getting closed now since the new installed will take care of this process.
