### ISSUE TITLE
Qual a senha root do mysql?

### ISSUE THREAD

**Issue by rodriguetes** [codecasts/ambientum#32]

**Comment by hernandev** [comment]
@rodriguetes

As senhas são setadas por variavel de ambiente: seguem as mesmas

```
    environment:
      - MYSQL_ROOT_PASSWORD=minha_senha_de_root
      - MYSQL_DATABASE=meu_banco_a_ser_criado
      - MYSQL_USER=meu_usuario_a_ser_criado
      - MYSQL_PASSWORD=minha_senha_a_ser_criada_para_usuario_acima

```

**Comment by rodriguetes** [comment]
Desculpe @hernandev , foi falta de atenção minha.

**Comment by hernandev** [comment]
@rodriguetes acontece, força ai!

**Comment by rodriguetes** [comment]
É porque esta ocorrendo o seguinte problema comigo, quando crio uma migrate e executo via artisan (`p php artisan migrate`) para criar as tabelas está ocorrendo o seguinte erro:

> [Illuminate\Database\QueryException]                                                                                                                                            
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known (SQL: select * from information_schema.tables where table_schema = sandbox and   
  table_name = migrations)

>[PDOException]                                                                                  
  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo failed: Name or service not known  
                                                                                                  

                                                                                               
 > [PDOException]                                                                               
  PDO::__construct(): php_network_getaddresses: getaddrinfo failed: Name or service not known 

Para outros comando via artisan como make::controller e outros está funcionando normalmente, segue meu composer e .env:

Docker Composer: [Link](http://pastebin.com/yw9RH0TX)

Env: 

> DB_CONNECTION=mysql
DB_HOST=mysql:3306
DB_PORT=3306
DB_DATABASE=sandbox
DB_USERNAME=sandbox
DB_PASSWORD=sandbox

database.php 

>'mysql' => [
            'driver' => 'mysql',
            'host' => env('DB_HOST', '127.0.0.1'),
            'port' => env('DB_PORT', '3306'),
            'database' => env('DB_DATABASE', 'forge'),
            'username' => env('DB_USERNAME', 'forge'),
            'password' => env('DB_PASSWORD', ''),
            'charset' => 'utf8',
            'collation' => 'utf8_unicode_ci',
            'prefix' => '',
            'strict' => true,
            'engine' => null,
        ],

Não sei o que pode ser, algumas pessoas disseram que pode ser permissão do usuário sandbox, entao estava tentando entrar como root, por isso lhe pedi a senha do root, mas enfim, sabe o que pode estar ocorrendo? Obrigado

**Comment by edbizarro** [comment]
@rodriguetes Isso as vezes acontece porque o docker não resolveu o seu host "mysql", mesmo em swarm mode isso acontece (pelo menos pra mim).

A solução que encontrei foi adicionar a linha `127.0.0.1     mysql` nop meu /etc/hosts

O mesmo vale pro redis, caso esteja usando

```
127.0.0.1       mysql
127.0.0.1       redis
```

**Comment by hernandev** [comment]
@edbizarro ambos os casos não são necessários. 

o host deve ser resolvido via docker-compose, cada serviço do `docker-compose.yml` vira um host e os mesmos precisam ser linkados pra serem vistos (verificar o arquivo de exemplo desse repositório)

os comandos p e n somente servem pra se criar projetos com composer e rodar utilitários, projetos devem ser rodados no docker-compose que se encarrega de resolver os hosts automaticamente

**Comment by edbizarro** [comment]
@hernandev sim, mesmo utilizando o docker-compose pra mim isso acontece, no meu caso foi necessário adicionar essas linhas no host (inclusive usando outras imagens, não necessariamente a do ambientum).

Não sei se é algum bug na versão do compose ou algo dele com o ubuntu 16.10, mas pra funcionar local aqui essa config foi necessária

**Comment by hernandev** [comment]
Mais provavel ser algum bug do compose ou do docker, pq existem relatos disso acontecer em algumas versões.

**Comment by hernandev** [comment]
fechando por inatividade
