### ISSUE TITLE
Docker container - Digital Ocean

### ISSUE THREAD

**Issue by willsilvano** [codecasts/ambientum#35]
Olá pessoal,

em ambiente local funciona perfeitamente para mim, quando executo 'docker-compose up -d' meu ambiente sobe, e o código da pasta atual vai pra dentro do container em /var/www/app.

Porém subindo um novo droplet na DigitalOcean e efetuando o comando citado os containers sobem mas parece que o código não é enviado para o droplet na Digital.

Segui esse artigo para montar os containers: https://docs.docker.com/machine/examples/ocean/#step-3-use-machine-to-create-the-droplet

**Comment by hernandev** [comment]
@willsilvano pode nos mostrar seu `docker-compose.yml`?

**Comment by willsilvano** [comment]
`
# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  packagefinder-postgres-data:
    driver: local

  # MySQL Data
  packagefinder-mysql-data:
    driver: local

  # Redis Data
  packagefinder-redis-data:
    driver: local

services:
  # Postgres (9.5)
  postgres:
    image: ambientum/postgres:9.6
    container_name: packagefinder-postgres
    volumes:
      - packagefinder-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=packagefinder
      - POSTGRES_DB=packagefinder
      - POSTGRES_USER=packagefinder

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: packagefinder-mysql
    volumes:
      - packagefinder-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=packagefinder
      - MYSQL_DATABASE=packagefinder
      - MYSQL_USER=packagefinder
      - MYSQL_PASSWORD=packagefinder

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: packagefinder-redis
    command: --appendonly yes
    volumes:
      - packagefinder-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-apache
    container_name: packagefinder-app
    volumes:
      - ~/code/php/package-finder:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: packagefinder-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache`

**Comment by willsilvano** [comment]
# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  packagefinder-postgres-data:
    driver: local

  # MySQL Data
  packagefinder-mysql-data:
    driver: local

  # Redis Data
  packagefinder-redis-data:
    driver: local

services:
  # Postgres (9.5)
  postgres:
    image: ambientum/postgres:9.6
    container_name: packagefinder-postgres
    volumes:
      - packagefinder-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=packagefinder
      - POSTGRES_DB=packagefinder
      - POSTGRES_USER=packagefinder

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: packagefinder-mysql
    volumes:
      - packagefinder-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=packagefinder
      - MYSQL_DATABASE=packagefinder
      - MYSQL_USER=packagefinder
      - MYSQL_PASSWORD=packagefinder

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: packagefinder-redis
    command: --appendonly yes
    volumes:
      - packagefinder-redis-data:/data
    ports:
      - "6379:6379"

  # PHP (with Caddy)
  app:
    image: ambientum/php:7.1-apache
    container_name: packagefinder-app
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.0
    container_name: packagefinder-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache

**Comment by willsilvano** [comment]
Estou usando o DockerTools no Windows. Pelo que andei procurando na internet, parece não estar conseguindo montar o volume conforme a pasta do meu computador. Subindo pela máquina "default" funciona no ambiente local, mas subindo a máquina que criei para a Digital fica a pasta vazia.

**Comment by hernandev** [comment]
Eu ainda não entendi o que você está tentando fazer?

Você está logando no droplet, colocando seu código lá, e ainda logado no droplet, subindo a ambiente,

ou

Você instalou o droplet no docker-machine e está subindo os containers localmente, com destino sendo o droplet?

**Comment by willsilvano** [comment]
Opa, vamos lá.

Eu criei uma máquina através do comando:

`docker-machine create --driver digitalocean --digitalocean-access-token xxxxx docker-sandbox`

Com isso, automaticamente foi criado um droplet no meu hub da digital ocean.

O que eu pretendia fazer, não sei se é possível, é fazer rodar a minha [aplicação](https://github.com/willsilvano/package-finder) local lá no droplet, usando o `docker-compose up -d`.

Aparentemente ao fazer isso os containers sobem no meu droplet, consigo conectar no Postgres e tudo mais, porém o código da minha aplicação é que não envia.

Ao acessar o endereço do meu droplet `http://<ip do droplet>:80`dá erro de Not Found. 

Parece que não está enviando o código do meu diretório do Windows: **~/code/php/packagefinder** para o container do php **/var/www/app** que está no droplet da digital ocean.

**Comment by hernandev** [comment]
@willsilvano não está e não irá.

Para que o código vá para o servidor remoto, você precisa que o mesmo faça parte da imagem.

Para isso que servem os sistemas de integracão continua.

uma forma de gerar uma imagem que contenha o seu código é criar um Dockerfile que adicione os arquivos.

Mas, se sua aplicacõa é simples, recomendo clonar os arquivos no servidor, e iniciar o docker-compose por lá.

Isso que você está tentando fazer não funciona mesmo não.

o docker-machine com host remoto só funciona pra rodar as imagens, não há sincronizacão de volumes não.

**Comment by willsilvano** [comment]
Entendi, @hernandev !
Muito obrigado pelo apoio!

**Comment by deyvisonrocha** [comment]
@willsilvano Você conseguiu fazer o que queria inicialmente? Fazendo o deploy no digital ocean da sua aplicação e utilizando o docker-compose ?
