### ISSUE TITLE
Instalação Laravel

### ISSUE THREAD

**Issue by raisiqueira** [codecasts/ambientum#37]
Em uma instalação Laravel, rodo meu `composer install` no container, ou local mesmo (no host)?

**Comment by hernandev** [comment]
Você pode rodar usando os comandos dos aliases, usando p como prefixo

`p composer install`

se for node, usando o prefixo n

`n npm install`

Se você já tem o projeto configurado com ambientum (docker-compose.yml), você pode rodar usando docker-compose

`docker-compose run [servico] composer install`

onde serviço é o nome do serviço dentro do docker-compose (o padrão é `web` ou `queue`)
