### ISSUE TITLE
Erro 404 contexto atual

### ISSUE THREAD

**Issue by raisiqueira** [codecasts/ambientum#38]
Estou fazendo apenas um teste com a imagem php7.1-nginx mapeando meu contexto atual para o container (.:/var/www/app) e no meu browser está retornando 404. Pode ser permissão no meu host?

![captura de tela de 2017-03-21 08-32-16](https://cloud.githubusercontent.com/assets/2914170/24145664/f708670a-0e10-11e7-892b-9a1204aaa448.png)

**Comment by hernandev** [comment]
Conseguiu resolver?

**Comment by raisiqueira** [comment]
Sim, só fiz apontar para a /var/www/app/public.
