### ISSUE TITLE
PHP 7.0-{web-server} images using PHP 7.1

### ISSUE THREAD

**Issue by edbizarro** [codecasts/ambientum#42]
Looking at https://github.com/codecasts/ambientum/blob/master/php/7.0-nginx/Dockerfile i notice that PHP 7.0 images with webservers are using wrong version of PHP (7.1)

**Comment by hernandev** [comment]
@edbizarro probably a mistake when I was building it. thanks for reporting.

**Comment by edbizarro** [comment]
submitted a PR for this :)
