### ISSUE TITLE
Try use local Dockerfile

### ISSUE THREAD

**Issue by zgelici** [codecasts/ambientum#47]
Hello,

In my app folder i have a docker-compose file, when i use this in the file:

  app:
    image: ambientum/php:7.1-apache
    container_name: groenenorm-app
    volumes:
      - .:/var/www/app

Everything is working great, but i want some modifications in apache. Because of this reason, i downloaded the files of this repository and added  the files i want to modify in the folder website.

Than i changed image to dockerfile. When i run it, it give me an error

app:
    build:
      context: ./
      dockerfile: webserver/7.0-apache/Dockerfile
    container_name: groenenorm-app
    volumes:
      - .:/var/www/app

The error i get is:

Building app
Step 1/13 : FROM ambientum/php:7.0
 ---> 26d0a2b16db2
Step 2/13 : MAINTAINER Vitor Souza <vsouza@virtualsystems.com.br>
 ---> Running in 7a1fc67a6b47
 ---> 0e85650b06a7
Removing intermediate container 7a1fc67a6b47
Step 3/13 : USER root
 ---> Running in d74131e8b262
 ---> b2d26897a85c
Removing intermediate container d74131e8b262
Step 4/13 : RUN echo "---> Adding contrib and non-free components in source.list" &&     sed -i "/main/s//main contrib non-free/" /etc/apt/sources.list &&     echo "--> Updating Repository and Installing Apache2" &&     apt-get update -y &&     apt-get install -y     apache2     apache2-mpm-worker     libapache2-mod-fastcgi &&     echo "--> Disabling mods we don't need, and enabling those who need" &&     a2dismod mpm_prefork mpm_event &&     a2enmod actions fastcgi alias mpm_worker rewrite &&     echo "--> Creating php7-fcgi" &&     touch /var/lib/apache2/fastcgi/php7-fcgi &&     echo "--> Cleaning up" &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* &&     echo "--> Fixing permissions" &&     chown -R php-user:php-user /var/run/apache2 &&     chown -R php-user:php-user /var/log/apache2 &&     chown -R php-user:php-user /var/lock/apache2 &&     chown -R php-user:php-user /var/lib/apache2
 ---> Running in a9e6ce354764
---> Adding contrib and non-free components in source.list
sed: /etc/apt/sources.list: No such file or directory
ERROR: Service 'app' failed to build: The command '/bin/sh -c echo "---> Adding contrib and non-free components in source.list" &&     sed -i "/main/s//main contrib non-free/" /etc/apt/sources.list &&     echo "--> Updating Repository and Installing Apache2" &&     apt-get update -y &&     apt-get install -y     apache2     apache2-mpm-worker     libapache2-mod-fastcgi &&     echo "--> Disabling mods we don't need, and enabling those who need" &&     a2dismod mpm_prefork mpm_event &&     a2enmod actions fastcgi alias mpm_worker rewrite &&     echo "--> Creating php7-fcgi" &&     touch /var/lib/apache2/fastcgi/php7-fcgi &&     echo "--> Cleaning up" &&     apt-get clean &&     rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/* &&     echo "--> Fixing permissions" &&     chown -R php-user:php-user /var/run/apache2 &&     chown -R php-user:php-user /var/log/apache2 &&     chown -R php-user:php-user /var/lock/apache2 &&     chown -R php-user:php-user /var/lib/apache2' returned a non-zero code: 1

does someone know how to fix this?

Thank you

**Comment by hernandev** [comment]
@zgelici Ambientum is not intended to be used as a build script on docker-compose but a ready for use image.

The problem here is that you're using apache image, that is not so well maintained as the nginx one.

I'll either update Apache version or drop support for it.

**Comment by hernandev** [comment]
closing by inactivity, reopen if you need any further help
