### ISSUE TITLE
Vote: Drop Caddy and Apache Support

### ISSUE THREAD

**Issue by hernandev** [codecasts/ambientum#51]
They're both good software, but maintaining and replicating features for both 3 servers is kinda hard.

I personally haven't used Apache on the last 4 years and Caddy needs some more expertise to be production compliant.

Caddy is more like a GO server and PHP support is not so great as on Nginx.

So I've opened this issue to let you guys know my intention of dropping support on those two servers, and to gather feedback from people using them, if I should keep them.

Let me know!

**Comment by jffsn** [comment]
Também não uso apache a uns 4 anos, atualmente uso nginx, nunca utilizei o caddy.

**Comment by edbizarro** [comment]
Apache não uso há anos, nginx uso no dia dia do trabalho, e caddy pra mim é o futuro, em todos meus projetos paralelos uso ele em prod e nunca tive problemas, pelo contrário, só facilidades

**Comment by wilcorrea** [comment]
I need use Apache to keep compatibility with hosts services. Apache is still popular between theirs. I vote to keep Apache : )

**Comment by hernandev** [comment]
Caddy is being officially dropped today, It's now licensed under Apache 2.0 only for source codes, to distribute Caddy with ambientum I would have to build the binaries and I'm neither using Caddy anymore or willing to mantain the builds.

If anyway uses Caddy, please migrate to Nginx as soon as possibe

**Comment by hernandev** [comment]
About apache support: Ambientum is mainly Laravel centric, meaning either project will have a default setting for url rewrites or will use the same rules as laravel does (like lumen for instance).

Symfony and other templates are being added for Nginx wich makes it harder to keep in Sync with Apache.

It will be kept here for legacy purposes for now, but anyone using it should change to Nginx as soon as possible.

**Comment by edbizarro** [comment]
Não encontrei onde diz que o caddy não pode ser distribuido caso não seja com binários compilados por quem queira distribuir.

Na minha opinião dropar o suporte ao caddy é um erro

**Comment by pedrommone** [comment]
👍  for dropping Caddy & Apache

**Comment by hernandev** [comment]
@edbizarro 

Announcement: https://caddyserver.com/blog/accouncing-caddy-commercial-licenses

EULA: https://github.com/mholt/caddy/blob/master/dist/EULA.txt

Treta: https://github.com/mholt/caddy/issues/1878

**Comment by edbizarro** [comment]
Too bad

:disappointed:

**Comment by vs0uz4** [comment]
@hernandev, já dropou o Caddy e o Apache?

**Comment by hernandev** [comment]
@vs0uz4 não, estão disponíveis por retro compatibilidade mas não estão mais recebendo atualizações

**Comment by hernandev** [comment]
Since Caddy was dropped, this issue is getting closed. Thank you all guys
