### ISSUE TITLE
Não consigo executar migrações

### ISSUE THREAD

**Issue by DiegoJG** [codecasts/ambientum#54]
Pessoal alguém já passou por isso? Não estou conseguindo executar as migrations no MYSQL nem no Postgres, conforme a imagem abaixo.

Abaixo da imagem colei o meu docker-compose.yml e por último meu .env do laravel.

Antecipadamente agradeço qualquer ajuda, ou tentativa  :+1: 

![image](https://user-images.githubusercontent.com/29586790/28070191-6904eb80-6622-11e7-8037-8b9d10bd0a9d.png)

``` ####
# ATENTION:
# Replace all occurences of erp with your project's name
####

# v2 syntax
version: '2'

# Named volumes
volumes:
  # Postgres Data
  erp-postgres-data:
    driver: local

  # MySQL Data
  erp-mysql-data:
    driver: local

  # Redis Data
  erp-redis-data:
    driver: local

services:
  # Postgres (9.5)
  postgres:
    image: ambientum/postgres:9.6
    container_name: erp-postgres
    volumes:
      - erp-postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=erp
      - POSTGRES_DB=erp
      - POSTGRES_USER=erp

  # MySQL (5.7)
  mysql:
    image: ambientum/mysql:5.7
    container_name: erp-mysql
    volumes:
      - erp-mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=erp
      - MYSQL_DATABASE=erp
      - MYSQL_USER=erp
      - MYSQL_PASSWORD=erp

  # Redis
  cache:
    image: ambientum/redis:3.2
    container_name: erp-redis
    command: --appendonly yes
    volumes:
      - erp-redis-data:/data
    ports:
      - "6379:6379"

  # PHP
  app:
    image: ambientum/php:7.1-nginx
    container_name: erp-api
    volumes:
      - .:/var/www/app
    ports:
      - "80:8080"
    links:
      - postgres
      - mysql
      - cache

  # Laravel Queues
  queue:
    image: ambientum/php:7.1
    container_name: erp-queue
    command: php artisan queue:listen
    volumes:
      - .:/var/www/app
    links:
      - mysql
      - cache 
```

Dados de conexão no .env do laravel:

```
DB_CONNECTION=mysql
DB_HOST=localhost
DB_DATABASE=erp
DB_USERNAME=erp
DB_PASSWORD=erp
```

**Comment by leogoncalves** [comment]
@DiegoJG Qual comando você está usando pra realizar as migrations?

**Comment by DiegoJG** [comment]
@leogoncalves 
```
p php artisan migrate
```

**Comment by leogoncalves** [comment]
Tente executar o comando usando docker exec. Eu pelo menos fiz isso um tempo atrás e funcionou.

**Comment by DiegoJG** [comment]
@leogoncalves  obrigado pela dica :+1: , mas infelizmente não tive sucesso, executei o comando:

```
docker exec erp-api php artisan migrate
```

O erro foi o mesmo da imagem que eu postei acima.

**Comment by DiegoJG** [comment]
Tentei à exaustão, não consegui identificar o problema :(

**Comment by deyvisonrocha** [comment]
Acontece o mesmo comigo. Está faltando a tabela `information_schema`. =(

**Comment by hernandev** [comment]
@DiegoJG @deyvisonrocha quando se usa o Docker, as imagens do Postgres e MySQL somente gerenciam o usuário / banco / senha na primeira inicialização.

Caso você altere os dados ali do env, dentro do `docker-compose.yml` o mesmo não será refletido a menos que seja a primeira inicialização.

Para que seja de fato refletido, você deve remover o volume anterior, assim zerando os dados que existiam antes da mudança.

Para remover os volumes:

1) Identifique o volume que está o postgresql, somente usar o comando `down` do docker-compose não irá resolver.

Para ver todos os volumes:

`docker volume ls`

2) Encontre o nome do volume a ser removido, e em seguinda, remova-o com o comando

`docker volume rm nome_do_volume_aqui`

**Comment by diego-goulart** [comment]
@hernandev obrigado pela ajuda, mas infelizmente não consegui fazer funcionar mesmo assim.
Eu deletei os volumes e em seguida executei o comando `docker-compose up -d`, ele montou os volumes novamente mas continua apresentando o mesmo erro citado acima pelo @deyvisonrocha 

Tem mais alguma coisa que podemos fazer? Obrigado!

**Comment by hernandev** [comment]
O db_host do .Env está errado, o PostgreSQL roda em outro container o host
correto é o nome do serviço

**Comment by hernandev** [comment]
`DB_HOST=postgres`

**Comment by diego-goulart** [comment]
@hernandev para MySQL também é o nome do serviço?

**Comment by hernandev** [comment]
o nome do serviço é o que você define no docker-compose.

veja vem:

```

services:

    meu-banco:
      image: mysql/posgresql/etc
      environment:
        DB_NAME=foobar

```

para esse exemplo, o host se chama `meu-banco`

.env
```
DB_HOST=meu-banco
```

**Comment by diego-goulart** [comment]
@hernandev  Entendi, mas agora deu outro problema, ele não conseguiu resolver o nome do serviço como um "host", veja.

![image](https://user-images.githubusercontent.com/17575204/28487350-cbf77ea2-6e64-11e7-85bb-70af202d5d82.png)

**Comment by diego-goulart** [comment]
@hernandev tentei inclusive adicionar uma refência no meu arquivo hosts para ver se dava certo.

**Comment by hernandev** [comment]
@diego-goulart @deyvisonrocha 

só como informação adicional.

cada serviço no arquivo `docker-compose.yml` é um container separado, e tem 1 IP separado, então por isso usar localhost não funciona.

**Comment by hernandev** [comment]
@diego-goulart seguinte cara, o comando de migracão, precisa ser rodado de dentro do container, você provavelmente está executando ele na sua maquina local

**Comment by hernandev** [comment]
o comando é:

`docker-compose run api php migrate`

**Comment by hernandev** [comment]
onde `app` é o nome do serviço onde está seu código, seguido do cmando que quer executar.

sintaxe é: `docker-compose run [servico] [comando]`

**Comment by diego-goulart** [comment]
@hernandev No meu ambiente local não tenho nada instalado.

Com o comando que você citou :` docker-compose run [servico] [comando]` deu certo :+1: 

Porém então vou ter que rever aqueles comandos dos atalhos como por exemplo: `p php artisan migrate`, porque com ele não funciona ainda ;(

**Comment by hernandev** [comment]
@diego-goulart esses comandos `p` e `n` são somente para tarefas como composer install e composer create project, quando voce já tem um projeto todo o fluxo se dá dentro do `docker-compose`

se quiser, voce pode adicionar alias pro docker-compose pra facilitar a vida

exemplo:

`alias artisan="docker-compose run app php artisan"`

depois basta rodar

`artisan migrate`

**Comment by diego-goulart** [comment]
@hernandev  Agora virei seu fã, obrigado cara.
Quando vier em Goiânia-GO me dá um alô que eu te pago uma coca :+1:

**Comment by hernandev** [comment]
@diego-goulart se for, cobrarei.

o que precisar pode contar sempre. fico feliz que no final tudo tenha dado certo.

se quiser se aprofundar no docker (e deve, pois essa porra tá tomando conta geral), leia o livro do nosso amigo @gomex: https://leanpub.com/dockerparadesenvolvedores

**Comment by diego-goulart** [comment]
@hernandev Opa obrigado pela dica, vou ler o livro do @gomex sim!  
Deu tudo certo sim, e no fim das contas era eu mesmo (leigo) o problema.

@deyvisonrocha  faça os procedimentos que o @hernandev  citou que vai dar certo

Obrigado.

**Comment by deyvisonrocha** [comment]
Se deu certo para você @diego-goulart com certeza vai funcionar aqui. Valeu @hernandev
