### ISSUE TITLE
p composer create não funciona no Git Bash no Windows.

### ISSUE THREAD

**Issue by andersonn-roberto** [codecasts/ambientum#56]
Estou tentando criar um projeto Laravel com o comando:
`p composer create laravel/laravel meu-projeto`
Porém, nada acontece.
Tentei utilizar no Ubuntu on Windows porém sem sucesso também.

**Comment by amaurycatelan** [comment]
Olá, boa noite! 
Não tenho muito conhecimento sobre o ambiente Windows, mas espero ajudar! 😄 

Algumas alternativas:
O que não funciona é só o _alias_ "p" OU o comando _docker_ em si? Já executou: 

```
source ~/.ambientum_rc
p
p php --version
```

Ou então executar diretamente a função:

```
function p() {
  winpty docker run -it --rm -v /$(pwd):/var/www/app -v /$A_COMPOSER:$A_PHP_HOME/.composer -v /$A_CONFIG:$A_PHP_HOME/.config -v /$A_CACHE:$A_PHP_HOME/.cache -v /$A_LOCAL:$A_PHP_HOME/.local -v /$A_SSH:$A_PHP_HOME/.ssh ambientum/php:7.1 "$@"
}

alias p=p
```
Algum erro é exibido ao executar esses comandos? 🤔

**Comment by andersonn-roberto** [comment]
Olá, bom dia @amaurycatelan e obrigado pelo comentário.

Nenhum erro é exibido, isso é o que me intriga.
Executei os testes sugeridos e nada acontece.
Vou deixar o comando executando até retornar o cursor ou acontecer outra coisa.

**Comment by hernandev** [comment]
existe um arquivo de source específico para o windows.

esse tipo de problema irá deixar de acontecer em breve, pois estou migrando os scripts para um binário node multi plataforma
