### ISSUE TITLE
Announcement: Dropping Caddy support

### ISSUE THREAD

**Issue by hernandev** [codecasts/ambientum#58]
Caddy is now only free for personal use, since the license is somehow confusing, and most people, including me, just use Nginx, we will be dropping the Caddy images in favor of Nginx.

Anyone using the images `php:7.0-caddy`, `php:7.1-caddy` or `php:latest-caddy` should use nginx versions instead.

**Comment by pedrommone** [comment]
👍  for dropping Caddy & Apache

**Comment by hernandev** [comment]
@pedrommone that's what's gonna happen indeed. Caddy sooner but Apache is on the line.

**Comment by hernandev** [comment]
Lot of time has passed, Caddy is now dead on Ambientum.

Closing this since the readme will not even list it there anymore.

Thank you all!
