### ISSUE TITLE
update yarn

### ISSUE THREAD

**Issue by viniciusss** [codecasts/ambientum#59]
### Yarn warning
```
warning Your current version of Yarn is out of date. The latest version is "1.0.2" while you're on "0.24.5".
```

### Container
```
docker pull ambientum/node:7
7: Pulling from ambientum/node
Digest: sha256:7437e3f6bbf5c10ff67721874fed8eca60a11080b468e6a4223ae12db17a5ac4
Status: Image is up to date for ambientum/node:7
```

**Comment by hernandev** [comment]
Both node and yarn got updated on all versions, ensure you update your images by pulling them with 

Use the one corresponding the image you're using

- `docker pull ambientum/node:latest`
- `docker pull ambientum/node:8`
- `docker pull ambientum/node:7`
- `docker pull ambientum/node:6`
