### ISSUE TITLE
Beanstalkd

### ISSUE THREAD

**Issue by edbizarro** [codecasts/ambientum#6]
any plans to add beanstalkd support?

**Comment by hernandev** [comment]
Probably in a few days, but ill need help testing since i do use redis only on my day to day projects.

I do know lado there is some monitor tool for beanstalkd, not sure the the name tough

**Comment by hernandev** [comment]
Support added, for both Beanstalkd and Beanstalkd Console

**Comment by julihermes** [comment]
How to configure in docker-compose.yml?

**Comment by hernandev** [comment]
@julihermes open a new issue
