### ISSUE TITLE
configure HTTPS doesnt work

### ISSUE THREAD

**Issue by zgelici** [codecasts/ambientum#61]
Hi,

I try to configure https.

i followed the steps from https://github.com/codecasts/ambientum/issues/46 (production)

Steps i did:
- Login into the server (SSH)
- created the folder (/home/ambientum/ssl)
- cd /home/ambientum/ssl
- openssl req -x509 -nodes \
   -days 3650 \
   -newkey rsa:2048 \
   -keyout nginx.key \
   -out nginx.crt \ 
   -subj  "/C=AM/ST=Ambientum/L=Ambientum/O=Ambientum/CN=*.nl"
- openssl dhparam -out dhparam.pem 2048
- docker-compose restart

can reach https.

who can help me, please

it says:
ERR_CONNECTION_REFUSED

nginx log
"ssl_stapling" ignored, issuer certificate not found for certificate

**Comment by emtudo** [comment]
You should add in your file docker-compose.yml
     volumes:
       - ./.ssl:/home/ambientum/ssl

".ssl" is the directory where your files are (nginx.key, nginx.crt and dhparam.pem)

**Comment by zgelici** [comment]
Thank you

**Comment by hernandev** [comment]
@zgelici HTTPS is bundled by default on the images for development and "behind a proxy" usage.

The port where HTTPS works is 8083 on the container, so you will need to map a second port there.

If're you planning on using the default HTTP and HTTPS ports.

Bind 80 on the host to 8080 on the container
Bind 443 on the host to 8083 on the container.

Mounting the volume and generating the new certificate is only useful for replacing the default certificate.
