### ISSUE TITLE
Redis version

### ISSUE THREAD

**Issue by mits87** [codecasts/ambientum#63]
Hi,

Is it possible to add new version of redis-server?
The latest version is 4.0.2 and will be great if ambientum/redis has also this version.

What are you thinking about it?

**Comment by vs0uz4** [comment]
@mits87,

PR (#64) with new version of redis submited.

**Comment by hernandev** [comment]
@vs0uz4 contributed the 4.0 version, but the official recomendation is to use official redis images.

Ambientum redis images are just "proxies" to the official ones, a way of easily remembering the image name.
