### ISSUE TITLE
Mongodb image

### ISSUE THREAD

**Issue by bsormagec** [codecasts/ambientum#68]
I think we need a MongoDB image in this ecosystem :) Thanks..

**Comment by hernandev** [comment]
@bsormagec I recommend using the official MongoDB image, from library/mongo. The services included within Ambientum will at some point die as well in favor of official images.

The images that will be kept here are the custom PHP and Node ones.

Thanks

**Comment by hernandev** [comment]
Closing this issue since MongoDB will not be included, since official working images are available at docker hub (https://hub.docker.com/_/mongo/)
