### ISSUE TITLE
Oracle extension support

### ISSUE THREAD

**Issue by marcus-campos** [codecasts/ambientum#74]
Requesting support for Oracle extension (oci)

**Comment by hernandev** [comment]
Hi, oracle support will be tested and bundled as soon as possible.

I do need some helping testing it, since I don't have a working install of oracle available and I intend to keep it that way hahahhaa

**Comment by marcus-campos** [comment]
I'll test and give you a feedback soon. Oracle is good (But very expensive hahahah).

**Comment by hernandev** [comment]
@marcus-campos From what I remember, ICI binaries are source closed right? So that means if I want to redistribute it, I would be required to relay the license agreement to every container that will run it.

Unless I'm wrong about the Licensing, that's not compatible with  this project own License, and may not be implemented since we arealy dropped Caddy support, and on Caddy's case it was just because the license wasn't clear enough at the time.

**Comment by pedrommone** [comment]
IMHO, stuff like that should be implemented by the user side, ambientum is getting bigger and we shall expect performance issues.

@hernandev maybe we can create some new documentation of how extend ambientum?

**Comment by hernandev** [comment]
@pedrommone please create a EXTENDING issue so we put that on the backlog, but, as far as I remember, Oracle will be hard to do since licensing may be prohibitive for us to distribute.

**Comment by hernandev** [comment]
keeping it open until I get a final review on this.

**Comment by marcus-campos** [comment]
Got it! I'll move on to the team and we'll find a solution to this. Thank you very much for the time provided.

**Comment by joaorobertopb** [comment]
Hi guys,

I need help installing php oci8 on alpine linux...

@marcus-campos could you please teach me how to do this?

**Comment by ivenspontes** [comment]
@joaorobertopb any progress?

**Comment by joaorobertopb** [comment]
@ivenspontes Not! :anguished:

**Comment by marcus-campos** [comment]
Hello @joaorobertopb , I left the company where I worked. Where I work today does not use oracle. When I was trying to mount a container for myself, I had many problems with the oracle instant client. I know it's possible to use oracle + php in docker, but I did not find a way to do it.

**Comment by marcus-campos** [comment]
@joaorobertopb I can help you by passing on the knowledge of where I had problems and some solutions to some of them. Send me an email (campos.v.marcus@gmail.com).

**Comment by joaorobertopb** [comment]
Nice!

@marcus-campos thank you very much for your help.
