### ISSUE TITLE
PHP 7.2

### ISSUE THREAD

**Issue by mits87** [codecasts/ambientum#76]
Hi, 

is it possible to bump latest version of php to 7.2 (also for nginx)? 
Thank you.

**Comment by hernandev** [comment]
Hi @mits87.

No, it's not, yet.

NewRelic and XDebug still do not support PHP 7.2 and releasing Ambientum without it would break people using those.

NewRelic is expected to support 7.2 on the first half of this month (january) and xDebug is about to be released.

As soon those components are available, I'll upgrade to PHP 7.2

If you are in a rush to support 7.2, you can just build the images without it, using PHP Alpine for 7.2

**Comment by mits87** [comment]
Thank you for your answer. I will waiting :)

**Comment by hernandev** [comment]
@mits87 PHP 7.2 is now available, inclusing support for Argon2 password hashing.

xDebug is still not stable, reason why the `latest` tag will remain pointing the 7.1 version.

If you don't need xDebug, go ahead on it.

Otherwise, stick with 7.1 a little bit

**Comment by mits87** [comment]
Thank you for the information. I will wait for xdebug.

**Comment by viniciusss** [comment]
@hernandev [2018-01-29] - Xdebug 2.6.0 is out!  - I test using: `RUN pecl install xdebug`
- https://xdebug.org/

**Comment by hernandev** [comment]
Already released several months ago :) forgot to close this.
Thank you guys!
