### ISSUE TITLE
Support for PHP-PM!

### ISSUE THREAD

**Issue by pedrommone** [codecasts/ambientum#78]
Would be nice a support for [PHP-PM](https://github.com/php-pm/php-pm). PHP-PM is kinda like NodeJS, it runs based on event loop, which make it super fast.

**Comment by hernandev** [comment]
https://github.com/codecasts/ambientum/issues/79

**Comment by hernandev** [comment]
This was already built sometime ago, but not yet docummented.

Thank you very much for the suggestion, PHP-PM is awesome.

If you want to use PHP-PM itself in a simple way inside Docker, take a look in another project: https://github.com/hernandev/ppm.phar this one is a bundler phar with php-pm

Cya
