### ISSUE TITLE
Improve extensibility with better documentation

### ISSUE THREAD

**Issue by pedrommone** [codecasts/ambientum#80]
A lot of users ask for common things that can be easily added with native `docker from` feature. 

Would be nice if we had something to teach how to install a new php extension or even an npm module.

**Comment by hernandev** [comment]
@pedrommone that's teaching docker itself, but makes sense since this project aims to be user-friendly.

Let me put some thought into it and see what we can do.

**Comment by hernandev** [comment]
Still haven't got the time, but something related to teaching the inner process of building production images may be something worth considering, but not this project scope directly.

Closing, but I'll do something aside related to the suggestion.

Thank you man!
