### ISSUE TITLE
SQLSTATE [HY000] [2002] Conexão recusada

### ISSUE THREAD

**Issue by zgelici** [codecasts/ambientum#85]
às vezes eu recebo esse erro

SQLSTATE [HY000] [2002] Conexão recusada

**Comment by atiladelcanton** [comment]
Estou tendo o mesmo problema!

**Comment by hernandev** [comment]
O problema é relacionado ao .env do Laravel, voce precisa especificar o host exatamente como está no docker-compose.yml.

Existem outras issues semelhantes (acho que umas 3 haha), então vou fechar essa.
