### ISSUE TITLE
Fresh project VUE won't work in dev

### ISSUE THREAD

**Issue by loooping** [codecasts/ambientum#91]
![captura de tela 2018-03-20 as 17 18 55](https://user-images.githubusercontent.com/29130032/37680664-591984ee-2c63-11e8-9b21-ec3521082d0b.png)

`$ n yarn dev` output:

```
 DONE  Compiled successfully in 34364ms                                                                                                                                    20:19:29

 I  Your application is running here: http://localhost:8080
```
But browse `http://localhost:8080` i have ERR_EMPTY_RESPONSE

Only works **production-server**

**Comment by loooping** [comment]
Solved https://github.com/webpack/webpack-dev-server/issues/547#issuecomment-284737321

**Comment by cichondev** [comment]
@loooping, this really solved, thanks!

**Comment by hernandev** [comment]
Problem is related to 127.0.0.1 vs 0.0.0.0 listening on the Node.JS process inside the container. Closing by resolution status. Thank you all!
