### ISSUE TITLE
Config and use Xdebug

### ISSUE THREAD

**Issue by mtferreira** [codecasts/ambientum#92]
Hey everyone!   

I saw that it is possible, but I am kind of lost and confused about this... 
so if possible, i would like some help about how to configure and use xdebug.

note: I already use it on the host machine.

thanks!

**Comment by hernandev** [comment]
I'll provide instructions on it.

TL;RD; you need to configure your IDE to listen for connections instead of starting xDebug, so the application running on Ambientum calls the host that is listening for it

**Comment by mtferreira** [comment]
I did not understand either.
I found this tutorial https://serversforhackers.com/c/getting-xdebug-working, but I did not understand and could not replicate in vscode.

**Comment by hernandev** [comment]
Hey guys, let's center the issue about xDebug on a single issue, I'm experimenting with some more simple configuration strategies.

Please follow up on #103
