### ISSUE TITLE
ERROR in npm install on "laravel/framework": "5.5.*"

### ISSUE THREAD

**Issue by vs0uz4** [codecasts/ambientum#97]
In my "Docker" development environment, I have the following scenario:

os : **Linux 4.15.13-1-ARCH x86_64 GNU/Linux**
docker : **18.03.0-ce** build **0520e24302**
docker-compose : **1.20.1**
Laravel Framework : **5.5.***
Node : **v8.10.0**
Npm : **5.8.0**
Yarn : **1.5.1**

my docker-compose.yml
https://pastebin.com/grse32Hk

my package.json
https://pastebin.com/8NgFEfZm

It turns out that when I run the following command, I get some errors.
```$ docker-compose run dev npm install```

in my terminal the following errors are displayed
https://pastebin.com/1p5MkG3F

an error logs file is generated in ambientum enviroment, such as:
```
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/ambientum/.npm/_logs/2018-04-08T12_21_28_740Z-debug.log
```
https://pastebin.com/3tQtCSgw
( as the generated file is giant, I have separated only the part of the error).

And if by chance I delete the `node_modules` folder and try to execute the command with Yarn, the same errors are presented, as the log follows.

```$ docker-compose run dev yarn```

yarn-error.log
https://pastebin.com/L1ipVsSy

Apparently the errors occur in the build of the following libraries:
**gifsicle@3.0.4
mozjpeg@5.0.0
optipng-bin@3.1.4
pngquant-bin@4.0.0**

Is someone else going through the same problems?

**Comment by vs0uz4** [comment]
The errors presented are:
gifsicle@3.0.4 -> Command failed: autoreconf -ivf (/bin/sh: autoreconf: not found)
mozjpeg@5.0.0 -> Command failed: autoreconf -fiv (/bin/sh: autoreconf: not found)
optipng-bin@3.1.4 ->Command failed: ./configure --with-system-zlib 
pngquant-bin@4.0.0 -> Error: pngquant failed to build, make sure that libpng-dev is installed

**Comment by hernandev** [comment]
Closing by inactivity. Thank you for using Ambientum! Be welcome to ask for help at any time.

This is an old issue, sorry for not being able to follow up on time.
