### ISSUE TITLE
SQLSTATE [HY000] [2002] Connection refused

### ISSUE THREAD

**Issue by atiladelcanton** [codecasts/ambientum#98]
I'm getting the connection error declined in laravel, I'm using the same credentials I use in my mysql

**Comment by hernandev** [comment]
you need to specify the mysql host as being the mysql container. the same name used on the docker-compose.yml file.

There are other issues on this repository explaining how

**Comment by hernandev** [comment]
Closing by inactivity and missing more details. Thank you for using Ambientum! Be welcome to ask for help at any time.
